### ISSUE TITLE
Parsing error with string: H&M

### ISSUE THREAD

**Issue by nberney** [mankyd/htmlmin#4]
Generates an error with the following string:

import htmlmin
htmlmin.minify('H&M')

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/htmlmin/main.py", line 93, in minify
    minifier.close()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.py", line 118, in close
    self.goahead(1)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.py", line 213, in goahead
    self.error("EOF in middle of entity or char ref")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.py", line 121, in error
    raise HTMLParseError(message, self.getpos())
HTMLParseError: EOF in middle of entity or char ref, at line 1, column 2

**Comment by tnsurender** [comment]
Is this issue resolved ? 
I am facing same issue .
